#!/usr/bin/env python3

# SPM-specific procurement niche ontology.
# Regex rules classify tender title/description/category text. Heuristic attributes are
# business assumptions, intentionally kept separate from empirical market metrics.

NICHE_RULES = [
    dict(macro='WEB_DIGITAL', niche='Website design / redesign', pattern=r'\b(web ?site|website|web design|site internet|site web|webseite|website redesign|refonte.{0,20}site|création.{0,20}site)\b', ai=.75, subcontract=.85, remote=.95, low_entry=.82, low_pain=.78, margin=.82),
    dict(macro='WEB_DIGITAL', niche='CMS development / migration', pattern=r'\b(cms|wordpress|drupal|typo3|joomla|content management system|migration.{0,20}(web|cms)|cms migration)\b', ai=.65, subcontract=.82, remote=.95, low_entry=.72, low_pain=.68, margin=.78),
    dict(macro='WEB_DIGITAL', niche='Website maintenance / content updates', pattern=r'\b(web(site)? maintenance|maintenance.{0,20}(web|site)|support.{0,20}(web|site)|content update|mise.{0,15}jour.{0,20}site|webbeheer|wartung.{0,20}website)\b', ai=.70, subcontract=.82, remote=.95, low_entry=.82, low_pain=.82, margin=.82),
    dict(macro='WEB_DIGITAL', niche='Web hosting / domain / SSL', pattern=r'\b(web hosting|hosting|hébergement.{0,20}(web|site)|webhosting|domain name|nom de domaine|ssl certificate|hosting services)\b', ai=.35, subcontract=.95, remote=.98, low_entry=.86, low_pain=.92, margin=.72),
    dict(macro='WEB_DIGITAL', niche='Web accessibility remediation', pattern=r'\b(web accessibility|digital accessibility|accessibilit.{0,15}(web|numérique|site)|wcag|eaa compliance|accessibility audit)\b', ai=.65, subcontract=.72, remote=.95, low_entry=.62, low_pain=.70, margin=.82),
    dict(macro='WEB_DIGITAL', niche='Microsites / campaign landing pages', pattern=r'\b(microsite|micro-site|landing page|campaign site|event website|project website|site événement|site campagne)\b', ai=.82, subcontract=.88, remote=.98, low_entry=.88, low_pain=.86, margin=.86),
    dict(macro='WEB_DIGITAL', niche='Online forms / lightweight portals', pattern=r'\b(online form|web form|digital form|formulaire en ligne|portal|portail web|citizen portal|registration portal|inscription en ligne)\b', ai=.70, subcontract=.78, remote=.94, low_entry=.66, low_pain=.68, margin=.82),
    dict(macro='CONTENT_DESIGN', niche='Graphic design / layout', pattern=r'\b(graphic design|graphisme|graphic services|layout design|mise en page|desktop publishing|dtp|grafisch ontwerp|grafische vormgeving)\b', ai=.82, subcontract=.92, remote=.98, low_entry=.92, low_pain=.88, margin=.84),
    dict(macro='CONTENT_DESIGN', niche='Annual report / publication layout', pattern=r'\b(annual report|rapport annuel|yearbook|activity report|rapport d.?activité|publication layout|report design|brochure design)\b', ai=.82, subcontract=.92, remote=.98, low_entry=.88, low_pain=.86, margin=.85),
    dict(macro='CONTENT_DESIGN', niche='Presentation / template design', pattern=r'\b(presentation design|powerpoint|slide deck|presentation template|template graphique|modèle de présentation|corporate template)\b', ai=.88, subcontract=.94, remote=.99, low_entry=.94, low_pain=.92, margin=.88),
    dict(macro='CONTENT_DESIGN', niche='Brand identity / visual identity', pattern=r'\b(brand identity|visual identity|identité visuelle|corporate identity|branding|brand guidelines|charte graphique|huisstijl)\b', ai=.75, subcontract=.88, remote=.98, low_entry=.82, low_pain=.80, margin=.86),
    dict(macro='CONTENT_DESIGN', niche='Illustration / infographics', pattern=r'\b(illustration|illustrator|infographic|infographie|data visuali[sz]ation|visualisation de données|icon design|pictogram)\b', ai=.90, subcontract=.90, remote=.99, low_entry=.90, low_pain=.90, margin=.86),
    dict(macro='CONTENT_DESIGN', niche='Copywriting / editorial content', pattern=r'\b(copywriting|copywriter|editorial content|content writing|rédaction|redaction|editorial services|web content|content creation|rédacteur)\b', ai=.88, subcontract=.90, remote=.99, low_entry=.90, low_pain=.89, margin=.86),
    dict(macro='CONTENT_DESIGN', niche='Proofreading / editing', pattern=r'\b(proofread|proofreading|copy edit|copyediting|editing service|relecture|correction.{0,15}(texte|document)|révision linguistique|lektorat)\b', ai=.86, subcontract=.92, remote=.99, low_entry=.92, low_pain=.93, margin=.82),
    dict(macro='CONTENT_DESIGN', niche='Social media content production', pattern=r'\b(social media content|social media management|réseaux sociaux|community management|content calendar|social content|instagram|linkedin content)\b', ai=.86, subcontract=.86, remote=.97, low_entry=.82, low_pain=.75, margin=.82),
    dict(macro='CONTENT_DESIGN', niche='Digital marketing / SEO / campaigns', pattern=r'\b(seo|search engine optimization|digital marketing|marketing digital|online campaign|digital campaign|paid social|google ads|sea campaign|référencement)\b', ai=.72, subcontract=.80, remote=.96, low_entry=.74, low_pain=.70, margin=.80),
    dict(macro='VIDEO_AUDIO', niche='Video production', pattern=r'\b(video production|film production|production vidéo|production audiovisuelle|corporate video|promotional video|institutional video|film institutionnel)\b', ai=.72, subcontract=.88, remote=.70, low_entry=.72, low_pain=.60, margin=.84),
    dict(macro='VIDEO_AUDIO', niche='Video editing / post-production', pattern=r'\b(video edit|video editing|post-production|post production|montage vidéo|montage audiovisuel|editing.{0,15}video)\b', ai=.88, subcontract=.94, remote=.99, low_entry=.90, low_pain=.88, margin=.88),
    dict(macro='VIDEO_AUDIO', niche='Animation / motion design', pattern=r'\b(motion design|motion graphics|animation video|animated video|2d animation|3d animation|vidéo animée|animation graphique)\b', ai=.90, subcontract=.92, remote=.99, low_entry=.86, low_pain=.84, margin=.90),
    dict(macro='VIDEO_AUDIO', niche='Photography', pattern=r'\b(photograph|photography|photographe|photographie|photo coverage|photo services|reportage photo)\b', ai=.45, subcontract=.94, remote=.20, low_entry=.86, low_pain=.76, margin=.78),
    dict(macro='VIDEO_AUDIO', niche='Subtitles / captions', pattern=r'\b(subtitl|captioning|closed caption|sous-titr|sous titr|ondertiteling|untertitel)\b', ai=.94, subcontract=.95, remote=.99, low_entry=.94, low_pain=.95, margin=.88),
    dict(macro='VIDEO_AUDIO', niche='Transcription / minutes', pattern=r'\b(transcription|verbatim|meeting minutes|minutes transcription|compte rendu|procès-verbal|speech to text|audio transcription)\b', ai=.96, subcontract=.96, remote=.99, low_entry=.95, low_pain=.96, margin=.90),
    dict(macro='VIDEO_AUDIO', niche='Voice-over / narration / audio editing', pattern=r'\b(voice.?over|narration|audio editing|podcast production|voice recording|enregistrement voix|sound editing|montage audio)\b', ai=.88, subcontract=.93, remote=.98, low_entry=.88, low_pain=.88, margin=.86),
    dict(macro='LANGUAGE', niche='Translation / localization', pattern=r'\b(translation|traduction|übersetzung|vertaling|locali[sz]ation|linguistic services|language services)\b', ai=.84, subcontract=.96, remote=.99, low_entry=.74, low_pain=.90, margin=.74),
    dict(macro='LANGUAGE', niche='Interpretation services', pattern=r'\b(interpreting|interpretation service|interprétation|interpreter|tolk|dolmetsch)\b', ai=.30, subcontract=.98, remote=.60, low_entry=.72, low_pain=.72, margin=.68),
    dict(macro='PRINT_BROKERAGE', niche='Brochure / flyer / poster printing', pattern=r'\b(printing|printing services|impression|drukwerk|druckerei|brochure|flyer|leaflet|poster printing|affiche|dépliant|folder printing)\b', ai=.22, subcontract=.99, remote=.88, low_entry=.88, low_pain=.90, margin=.78),
    dict(macro='PRINT_BROKERAGE', niche='Newsletter / magazine production', pattern=r'\b(newsletter|municipal magazine|city magazine|magazine printing|bulletin municipal|journal communal|gemeenteblad|periodical publication)\b', ai=.58, subcontract=.96, remote=.90, low_entry=.82, low_pain=.82, margin=.82),
    dict(macro='PRINT_BROKERAGE', niche='Direct mail / envelope / routing', pattern=r'\b(direct mail|mailing service|envelop|mise sous pli|routage|fulfilment mailing|postal distribution|mail fulfilment)\b', ai=.20, subcontract=.99, remote=.78, low_entry=.82, low_pain=.78, margin=.72),
    dict(macro='PRINT_BROKERAGE', niche='Signage / wayfinding / vinyl', pattern=r'\b(signage|wayfinding|signalétique|signaletique|vinyl graphics|window graphics|sign printing|panneaux|enseignes|belettering)\b', ai=.28, subcontract=.98, remote=.55, low_entry=.82, low_pain=.72, margin=.80),
    dict(macro='PRINT_BROKERAGE', niche='Promotional merchandise / branded items', pattern=r'\b(promotional item|promotional product|merchandise|goodies|objets publicitaires|branded items|giveaway|corporate gifts)\b', ai=.18, subcontract=.99, remote=.90, low_entry=.88, low_pain=.88, margin=.76),
    dict(macro='PRINT_BROKERAGE', niche='Labels / stickers / QR materials', pattern=r'\b(label printing|labels|stickers|sticker printing|étiquette|etiketten|qr code|qr-code|decals)\b', ai=.28, subcontract=.99, remote=.92, low_entry=.90, low_pain=.92, margin=.78),
    dict(macro='DATA_ADMIN', niche='Data entry / back-office processing', pattern=r'\b(data entry|data capture|saisie de données|back.?office processing|data input|administrative processing|encodage de données)\b', ai=.94, subcontract=.95, remote=.99, low_entry=.94, low_pain=.94, margin=.88),
    dict(macro='DATA_ADMIN', niche='Document digitization / scanning', pattern=r'\b(digiti[sz]ation|digitisation|numérisation|scanning service|document scanning|archive scanning|digital archiving|digitalisation d.?archives)\b', ai=.72, subcontract=.95, remote=.55, low_entry=.84, low_pain=.82, margin=.82),
    dict(macro='DATA_ADMIN', niche='Document conversion / PDF remediation', pattern=r'\b(document conversion|pdf conversion|accessible pdf|pdf remediation|ocr service|format conversion|conversion de documents|document remediation)\b', ai=.94, subcontract=.95, remote=.99, low_entry=.92, low_pain=.95, margin=.90),
    dict(macro='DATA_ADMIN', niche='Data cleaning / deduplication', pattern=r'\b(data clean|data cleansing|deduplication|data quality|nettoyage de données|data validation|data normalization|data normalisation)\b', ai=.92, subcontract=.88, remote=.99, low_entry=.82, low_pain=.84, margin=.90),
    dict(macro='DATA_ADMIN', niche='Survey data processing / coding', pattern=r'\b(survey processing|survey data|questionnaire processing|coding responses|enquête.{0,20}traitement|survey coding|data coding)\b', ai=.88, subcontract=.90, remote=.98, low_entry=.84, low_pain=.86, margin=.84),
    dict(macro='DATA_ADMIN', niche='Cataloguing / indexing / metadata', pattern=r'\b(catalogu|cataloging|cataloguing|indexing service|metadata creation|metadata enrichment|indexation|catalogage)\b', ai=.84, subcontract=.88, remote=.94, low_entry=.80, low_pain=.86, margin=.82),
    dict(macro='AUTOMATION_SOFTWARE', niche='Workflow automation / RPA', pattern=r'\b(workflow automation|process automation|rpa\b|robotic process automation|automatisation.{0,20}process|business process automation)\b', ai=.94, subcontract=.78, remote=.98, low_entry=.66, low_pain=.70, margin=.92),
    dict(macro='AUTOMATION_SOFTWARE', niche='AI chatbot / assistant', pattern=r'\b(chatbot|virtual assistant|ai assistant|conversational ai|assistant virtuel|generative ai|artificial intelligence assistant)\b', ai=.99, subcontract=.78, remote=.99, low_entry=.62, low_pain=.68, margin=.94),
    dict(macro='AUTOMATION_SOFTWARE', niche='Simple API / software integration', pattern=r'\b(api integration|software integration|system integration|interface development|data integration|intégration.{0,20}(logiciel|api|système)|interoperability)\b', ai=.82, subcontract=.76, remote=.97, low_entry=.62, low_pain=.60, margin=.90),
    dict(macro='AUTOMATION_SOFTWARE', niche='Low-code / no-code implementation', pattern=r'\b(low.?code|no.?code|power apps|power automate|microsoft forms|sharepoint automation|appsheet|bubble\.io)\b', ai=.92, subcontract=.80, remote=.99, low_entry=.72, low_pain=.76, margin=.92),
    dict(macro='TRAINING', niche='E-learning / training content', pattern=r'\b(e-learning|elearning|online training content|training module|digital learning|learning module|formation en ligne|module de formation)\b', ai=.86, subcontract=.86, remote=.98, low_entry=.76, low_pain=.78, margin=.86),
    dict(macro='EVENT_MEDIA', niche='Event audiovisual / livestream', pattern=r'\b(live stream|livestream|streaming event|audiovisual event|event av|webcast|captation.{0,15}(événement|event)|hybrid event)\b', ai=.58, subcontract=.96, remote=.35, low_entry=.76, low_pain=.56, margin=.80),
    dict(macro='EVENT_MEDIA', niche='Event communication materials', pattern=r'\b(event materials|event communication|conference materials|event branding|congress materials|salon.{0,15}(support|communication)|stand graphics)\b', ai=.62, subcontract=.96, remote=.70, low_entry=.84, low_pain=.72, margin=.82),
    dict(macro='RESEARCH_ADMIN', niche='Online survey setup', pattern=r'\b(online survey|survey platform|questionnaire en ligne|web survey|survey tool|consultation platform|public consultation survey)\b', ai=.82, subcontract=.82, remote=.99, low_entry=.80, low_pain=.84, margin=.84),
    dict(macro='RESEARCH_ADMIN', niche='Desk research / information collection', pattern=r'\b(desk research|market research support|information collection|data collection services|research support|documentary research|recherche documentaire)\b', ai=.84, subcontract=.84, remote=.98, low_entry=.78, low_pain=.78, margin=.84),
    dict(macro='PROCUREMENT_BROKERAGE', niche='Small IT equipment supply', pattern=r'\b(laptop|computer equipment|it equipment|monitor|tablet|computer peripherals|équipement informatique|matériel informatique|hardware supply)\b', ai=.10, subcontract=.98, remote=.80, low_entry=.70, low_pain=.78, margin=.48),
    dict(macro='PROCUREMENT_BROKERAGE', niche='Office / presentation equipment supply', pattern=r'\b(projector|presentation equipment|office equipment|display screen|digital signage screen|meeting room equipment)\b', ai=.10, subcontract=.98, remote=.75, low_entry=.72, low_pain=.76, margin=.52),
]

# Signals are text-presence proxies, not proof of a mandatory requirement.
ENTRY_SIGNAL_PATTERNS = {
    'turnover_or_financial_capacity': r'\b(turnover|annual turnover|chiffre d.?affaires|financial capacity|capacité financière|umsatz)\b',
    'iso_or_certification': r'\b(iso ?[0-9]{4,5}|certification|certified|certificat|accreditation|agrément|accréditation)\b',
    'insurance': r'\b(professional indemnity|liability insurance|insurance coverage|assurance responsabilité|assurance professionnelle)\b',
    'prior_references': r'\b(reference projects|references required|références similaires|previous experience|similar contracts|track record|referenties)\b',
    'staff_minimum': r'\b(minimum staff|minimum team|employees required|fte|full.?time equivalent|effectif minimum|équipe minimale)\b',
    'security_clearance': r'\b(security clearance|classified information|habilitation de sécurité|security vetting|screening clearance)\b',
    'local_or_onsite': r'\b(on.?site|onsite|site visit|local presence|présence locale|sur site|visite obligatoire|physical presence)\b',
    'framework_or_prequalification': r'\b(framework agreement|framework contract|accord.?cadre|dynamic purchasing system|dps\b|qualification system|pre.?qualification)\b',
}

STOPWORDS = {
    'the','and','for','with','from','this','that','services','service','supply','provision','contract','framework','public','procurement','purchase','tender','market','procedure','lot','lots',
    'de','des','du','la','le','les','et','pour','avec','dans','sur','une','un','dun','dune','prestations','prestation','fourniture','fournitures','marché','marche','accord','cadre',
    'der','die','das','und','für','mit','von','den','dem','des','leistung','leistungen','lieferung','beschaffung','auftrag',
    'van','voor','met','het','een','diensten','dienst','levering','opdracht','aanbesteding'
}
